theme: jekyll-theme-cayman

# Site Settings
locale                   : "de-DE"
title                    : "CLOUDETEER BLOG"
title_separator          : "-"
name                     : &name "Cloudeteer GmbH"
description              : &description "All about Multi Cloud architectures & modern operations"
url                      : https://cloudeteer.github.io
baseurl                  : "/blog"
breadcrumbs              : false # true, false (default)
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts

# Social Sharing
twitter:
  username               : &twitter "cloudeteer"
facebook:
  username               :
  app_id                 :
  publisher              :

    # Site Author
author:
  name             : "Cloudeteer GmbH"
  avatar           : # "profile.png"
  bio              : "https://cloudeteer.de/ueber_uns.php"
  location         : "Germany, Hamburg"
  employer         :
  pubmed           : # "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : 
  email            :
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "https://www.facebook.com/cloudeteergmbh/"
  foursquare       :
  github           : "cloudeteer"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         :
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "cloudeteer"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :